# Project information
site_name: 'SUMO Doc.'
site_description: 'SUMO Documentataion'
site_author: 'The SUMO Team'
site_url: 'https://jongrumer.github.io/sumo-doc'

# Repository
repo_name: 'jongrumer/sumo-doc'
repo_url: 'https://github.com/jongrumer/sumo-doc'

# Copyright
copyright: 'Copyright &copy; 2019 The SUMO Team'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'dark orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  search:
    language: 'en, sv' 

# Extensions
markdown_extensions:
  - footnotes        # Footnote support. Usage: Lorem ipsum[^1]
  - codehilite:      # Highlight code. Usage: ``` python
      linenums: true
  - admonition       # Add block-support. Usage: !!! <keyword> <newline> block of text
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # PyMedown Extensions
  - pymdownx.arithmatex # Latex Math!
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
 
# Navigation
nav:
    - Home: index.md
    - Installation: installation.md
    - Anders' readme: anders_readme.md
